// Code generated by MockGen. DO NOT EDIT.
// Source: raft/api/service.go

// Package api is a generated GoMock package.
package api

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	param "github.com/xmh1011/go-raft/param"
)

// MockRaftService is a mock of RaftService interface.
type MockRaftService struct {
	ctrl     *gomock.Controller
	recorder *MockRaftServiceMockRecorder
}

// MockRaftServiceMockRecorder is the mock recorder for MockRaftService.
type MockRaftServiceMockRecorder struct {
	mock *MockRaftService
}

// NewMockRaftService creates a new mock instance.
func NewMockRaftService(ctrl *gomock.Controller) *MockRaftService {
	mock := &MockRaftService{ctrl: ctrl}
	mock.recorder = &MockRaftServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRaftService) EXPECT() *MockRaftServiceMockRecorder {
	return m.recorder
}

// AppendEntries mocks base method.
func (m *MockRaftService) AppendEntries(args *param.AppendEntriesArgs, reply *param.AppendEntriesReply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendEntries", args, reply)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendEntries indicates an expected call of AppendEntries.
func (mr *MockRaftServiceMockRecorder) AppendEntries(args, reply interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEntries", reflect.TypeOf((*MockRaftService)(nil).AppendEntries), args, reply)
}

// ClientRequest mocks base method.
func (m *MockRaftService) ClientRequest(args *param.ClientArgs, reply *param.ClientReply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientRequest", args, reply)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClientRequest indicates an expected call of ClientRequest.
func (mr *MockRaftServiceMockRecorder) ClientRequest(args, reply interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientRequest", reflect.TypeOf((*MockRaftService)(nil).ClientRequest), args, reply)
}

// InstallSnapshot mocks base method.
func (m *MockRaftService) InstallSnapshot(args *param.InstallSnapshotArgs, reply *param.InstallSnapshotReply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallSnapshot", args, reply)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallSnapshot indicates an expected call of InstallSnapshot.
func (mr *MockRaftServiceMockRecorder) InstallSnapshot(args, reply interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallSnapshot", reflect.TypeOf((*MockRaftService)(nil).InstallSnapshot), args, reply)
}

// RequestVote mocks base method.
func (m *MockRaftService) RequestVote(args *param.RequestVoteArgs, reply *param.RequestVoteReply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestVote", args, reply)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestVote indicates an expected call of RequestVote.
func (mr *MockRaftServiceMockRecorder) RequestVote(args, reply interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestVote", reflect.TypeOf((*MockRaftService)(nil).RequestVote), args, reply)
}
