name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: UTCOVERPKG=$(go list ./... | grep -vE "vendor|example|mock") && go test -race -timeout=2m -v -cover -coverprofile=coverage.txt -coverpkg=$(echo $UTCOVERPKG | tr ' ' ',') $UTCOVERPKG | tee unittest.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
